### ISSUE TITLE
Problem reading pre-train models from Model Zoo

### ISSUE THREAD

**Issue by andres-ramirez27** [facebookresearch/SlowFast#354]
Hello. I'm testing different pre-train networks you offer on [MODEL_ZOO.md](https://github.com/facebookresearch/SlowFast/blob/master/MODEL_ZOO.md). When I'm loading different model using pickle (as they are in caffe2), it returns an integer; this later results in an error as an integer doesn't have key-values.

My environment corresponds to a docker container, generated from `pytorch/pytorch:1.7.0-cuda11.0-cudnn8-runtime` image available in Docker Hub, running Ubuntu 18.04.5 LTS and with the needed dependencies stated in the [INSTALL.md](https://github.com/facebookresearch/SlowFast/blob/master/INSTALL.md). Important dependencies version to mention:

- pickle == 4.0
- python == 3.8.3
- torch == 1.7.0

My hardware is:

- Nvidia GeForce GTX 1050Ti
- Intel i7-7700HQ CPU @ 2.80GHz

This happens specifically in the lines 213-215 from the `slowfast/utils/checkpoint.py`, in the `load_checkpoint` function.

```
213    if convert_from_caffe2:
214        with g_pathmgr.open(path_to_checkpoint, "rb") as f:
215            caffe2_checkpoint = pickle.load(f, encoding="latin1")
```

`caffe2_checkpoint` is an int, so when it tries access the keys from the dictionary, it fails (line 218):

```
218        for key in caffe2_checkpoint["blobs"].keys():
```

The `caffe2_checkpoint` is an integer for some model. Among the tested models with this behavior, are:

- SLOWFAST_64x2_R101_50_50.pkl
- SLOWFAST_8x8_R50_stepwise_multigrid.pkl
- SLOWFAST_8x8_R50_stepwise.pkl

Other tested model that return the __correct__ object (dictionary), are:

- SLOWFAST_8x8_R50.pkl
- SLOWFAST_4x16_R50.pkl
- SLOWFAST_32x2_R101_50_50.pkl
- SLOWFAST_32x2_R101_50_50_v2.1.pkl

The command I'm using is:

```
python3 slowfast/tools/run_net.py \
--cfg \ 
slowfast/configs/AVA/c2/SLOWFAST_64x2_R101_50_50.yaml \
TEST.DATASET ava \
DATA.PATH_TO_DATA_DIR PATH_TO_DATA_DIR \
AVA.ANNOTATION_DIR annotations \
AVA.LABEL_MAP_FILE ava_action_list_v2.2.pbtxt \
AVA.GROUNDTRUTH_FILE ava_val_v2.2.csv \
AVA.EXCLUSION_FILE ava_val_excluded_timestamps_v2.2.csv \
AVA.TEST_PREDICT_BOX_LISTS [' "ava_val_predicted_boxes.csv" ']
AVA.FRAME_DIR frames \
AVA.FRAME_LIST_DIR frame_lists \
AVA.TEST_LISTS [' "val.csv" '] \
TEST.CHECKPOINT_FILE_PATH path/to/SLOWFAST_64x2_R101_50_50.pkl \
TEST.CHECKPOINT_TYPE caffe2
TRAIN.ENABLE False \
TEST.ENABLE True \
DATA.NUM_FRAMES 16 \
NUM_GPUS 1
```

I would like to confirm if the problem is only on my end or the `.pkl` files have the problem.

**Comment by YaoFANGUK** [comment]
I encountered the same problem when i use model of 'SLOWFAST_64x2_R101_50_50.pkl'.
`for key in caffe2_checkpoint["blobs"].keys():
TypeError: 'int' object is not subscriptable`

**Comment by exnx** [comment]
I have the same problems....!!! So annoying.

**Comment by huang-chenhai** [comment]
I encountered the same problem as you, and it has been solved. The reason is that the Pretrained Model should be downloaded instead of downloading the model.Their names are the same.

**Comment by coldmanck** [comment]
> I encountered the same problem as you, and it has been solved. The reason is that the Pretrained Model should be downloaded instead of downloading the model.Their names are the same.

Do you mean they accidentally put the pretrained model weights as trained weights, and vice versa? If yes, It's ridiculous  that until now (January 2022) it's still not been fixed! It's FAIR...

**Comment by kuangxiaoye** [comment]
> I encountered the same problem as you, and it has been solved. The reason is that the Pretrained Model should be downloaded instead of downloading the model.Their names are the same.

https://dl.fbaipublicfiles.com/pyslowfast/model_zoo/ava/pretrain/SLOWFAST_32x2_R101_50_50.pkl


你救了我的命哈哈哈哈哈哈哈

裂开了 他这里怎么搞的这么混淆

**Comment by kuangxiaoye** [comment]
> 怎么感觉看这个的都是中国人，中国人用英语交流，可太逗了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年3月22日(星期二) 晚上9:47 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [facebookresearch/SlowFast] Caffe2_checkpoint is integer when loading pre-train models (#354) I encountered the same problem as you, and it has been solved. The reason is that the Pretrained Model should be downloaded instead of downloading the model.Their names are the same. https://dl.fbaipublicfiles.com/pyslowfast/model_zoo/ava/pretrain/SLOWFAST_32x2_R101_50_50.pkl 你救了我的命哈哈哈哈哈哈哈 裂开了 他这里怎么搞的这么混淆 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

哈哈哈哈哈本来就都是中国人

然后我看你们都用英文哈哈哈哈

笑死我了 

我每次都直接打中文  然后原地把整栋楼都炸成红的 全是中国人哈哈哈哈

**Comment by EiEM233** [comment]
> > 怎么感觉看这个的都是中国人，中国人用英语交流，可太逗了
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2022年3月22日(星期二) 晚上9:47 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [facebookresearch/SlowFast] Caffe2_checkpoint is integer when loading pre-train models (#354) I encountered the same problem as you, and it has been solved. The reason is that the Pretrained Model should be downloaded instead of downloading the model.Their names are the same. https://dl.fbaipublicfiles.com/pyslowfast/model_zoo/ava/pretrain/SLOWFAST_32x2_R101_50_50.pkl 你救了我的命哈哈哈哈哈哈哈 裂开了 他这里怎么搞的这么混淆 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 哈哈哈哈哈本来就都是中国人
> 
> 然后我看你们都用英文哈哈哈哈
> 
> 笑死我了
> 
> 我每次都直接打中文 然后原地把整栋楼都炸成红的 全是中国人哈哈哈哈

别说了，我也遇到这个bug了，哈哈哈哈哈哈

**Comment by geyaping** [comment]
> > > 怎么感觉看这个的都是中国人，中国人用英语交流，可太逗了
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2022年3月22日(星期二) 晚上9:47 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [facebookresearch/SlowFast] Caffe2_checkpoint is integer when loading pre-train models (#354) I encountered the same problem as you, and it has been solved. The reason is that the Pretrained Model should be downloaded instead of downloading the model.Their names are the same. https://dl.fbaipublicfiles.com/pyslowfast/model_zoo/ava/pretrain/SLOWFAST_32x2_R101_50_50.pkl 你救了我的命哈哈哈哈哈哈哈 裂开了 他这里怎么搞的这么混淆 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > 
> > 
> > 哈哈哈哈哈本来就都是中国人
> > 然后我看你们都用英文哈哈哈哈
> > 笑死我了
> > 我每次都直接打中文 然后原地把整栋楼都炸成红的 全是中国人哈哈哈哈
> 
> 别说了，我也遇到这个bug了，哈哈哈哈哈哈

me too，哈哈哈哈哈

**Comment by 3210448723** [comment]
哈哈，纯小白，我看的这个[视频讲解](https://www.bilibili.com/video/BV1su4y1Q7n3?t=248.6&p=13)，但是也遇到了同样问题
